### PR TITLE
Create gentx-molla202.json

### PR DESCRIPTION
**Pull request by molla202**
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"molla202","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.050000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.100000000000000000"},"min_self_delegation":"1","delegator_address":"empower1ut8qdryqjlrhgfup20yuvmgtpa5892gnllgz92","validator_address":"empowervaloper1ut8qdryqjlrhgfup20yuvmgtpa5892gn8ykdtl","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"bnoEZLaq1YUHZDXiGvAdLxJ0mcoIeY58RSFygLEHlvE="},"value":{"denom":"umpwr","amount":"1000000"}}],"memo":"db7f93182cf9d1c4ac5f7269eb38492870c27651@104.248.172.190:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A/WJPVhPe8jY6bTMTRdOE7Vb3GwAeWiD7ojC6thn4r1C"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":["Z4xPsIC04/1redW+Q8XZyKTps/SrTC8hKNo8o4MIfaZXcdpucnrBSOqqxXCvUlTOuOPp4HChKK/esvurHTy6JQ=="]}

### CODE REVIEW

**Comment by molla202** [comment]
abecimolla#6640

**Comment by bjaanes** [comment]
Thank you for the PR, I will have to close it for now, but read the message below and join our Discord while we regroup and get ready for the next round.

We just started the testnet with a small number of validators to make sure we could coordinate a smooth launch.
The criteria were simple: experience, willingness to help, and most importantly, first come first serve (after the other criteria were satisfied).
This is not going to be the end of the validator selection obviously. We only have 20 so far in gentx. We will be asking for help on certain things for the testnet going forward, and we will start sending out some forms to get a better understanding of the potential validators.  I will keep you all updated on that process.

We will be opening up a faucet tomorrow (it is being tweaked and finalized right now) which will allow for anyone to start validating and testing as well.
There will be an opportunity to get some delegations from us to solidify yourself in the validator set and get gentx for the next testnet (again, help will be asked for).

I will be closing all gentx PRs for now and we can get back to that for the next round. For now, join the testnet with  #faucet (tomorrow) and we will keep you updated. There is no need to ask for gentx at this time 🙂 But do not worry, because there is plenty of time to get in 🙂

**Comment by molla202** [comment]
thanks

**Comment by molla202** [comment]
image

**Pull request closed without merging**
